# Generated by Django 4.2.3 on 2023-07-06 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermembership',
            old_name='memebership_type',
            new_name='membership_type',
        ),
    ]
